# Generated by Django 5.2.8 on 2025-11-18 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('diretor', models.CharField(max_length=255)),
                ('ano', models.PositiveIntegerField()),
                ('genero', models.CharField(max_length=100)),
                ('duracao', models.PositiveIntegerField()),
            ],
        ),
    ]
